apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go
  template:
    metadata:
      labels:
        name: go
    spec:
      containers:
        - name: hello-world-go
          image: pascalallen/hello-world-go
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9990